### ISSUE TITLE
Consider to update the screen-reader-text class based on new browsers support

### ISSUE THREAD

**Issue by afercia** [wpaccessibility/a11ythemepatterns#11]
See https://github.com/wpaccessibility/a11ythemepatterns/pull/10#issuecomment-296765769

The re-factoring should take into account the end of support for IE 8-9-10 announced for WordPress 4.8. See 
https://make.wordpress.org/core/2017/04/23/target-browser-coverage/
> we are officially ending support for Internet Explorer versions 8, 9, and 10, starting with WordPress 4.8

**Comment by skorasaurus** [comment]
When you're talking about updating it; are you referring to:
what's in themes like Twenty-Nineteen; 
what's in wordpress core ([example](https://github.com/WordPress/WordPress/blob/master/wp-includes/css/wp-embed-template.css)); 
or what's available within the [Accessibility Handbook](https://make.wordpress.org/accessibility/handbook/markup/the-css-class-screen-reader-text/)

**Comment by samikeijonen** [comment]
It's been updated to Core and similar example is in the handbook. With that said, I'm not sure is anyone updating this repo.

**Comment by afercia** [comment]
This repo, example:

https://github.com/wpaccessibility/a11ythemepatterns/blob/b36ce6b8e8af39139f35d9a8029cc1a1cf65c2c1/dropdown-menus/vanilla-js/style.css#L56-L63

Also the one in the read-more-link needs some minor adjustment:

https://github.com/wpaccessibility/a11ythemepatterns/blob/b36ce6b8e8af39139f35d9a8029cc1a1cf65c2c1/read-more-links/style.css#L1-L13

The one in core is the most up-to-date one to copy from. Thanks.
