### ISSUE TITLE
New Pattern: Make a Basic Responsive Menu Pattern

### ISSUE THREAD

**Issue by davidakennedy** [wpaccessibility/a11ythemepatterns#4]
[Amanda Rush](https://profiles.wordpress.org/arush/) is leading this pattern. If you want to help, get in touch with her or comment here.

**Comment by amandarush** [comment]
I have the one for Genesis, but we need this also for non-Genesis themes
that go in the repo. If anyone wants to assist with that let me know.

_From:_ David A. Kennedy [mailto:notifications@github.com]
_Sent:_ Sunday, March 22, 2015 10:01 PM
_To:_ wpaccessibility/a11ythemepatterns
_Subject:_ [a11ythemepatterns] New Pattern: Make a Basic Responsive Menu
Pattern (#4)

Amanda Rush https://profiles.wordpress.org/arush/ is leading this
pattern. If you want to help, get in touch with her.

—
Reply to this email directly or view it on GitHub
https://github.com/wpaccessibility/a11ythemepatterns/issues/4.

**Comment by davidakennedy** [comment]
@amandarush No problem. I'm happy to create the non-Genesis one from your Genesis code. Do you need help committing the code for the Genesis one? I'm happy to help there as well. Just let me know!

**Comment by amandarush** [comment]
Is the menu repo already created, or do I need to log in, create it, pull
it down, add the code, and then push back up?

_From:_ David A. Kennedy [mailto:notifications@github.com]
_Sent:_ Monday, March 23, 2015 7:47 PM
_To:_ wpaccessibility/a11ythemepatterns
_Cc:_ Amanda Rush
_Subject:_ Re: [a11ythemepatterns] New Pattern: Make a Basic Responsive
Menu Pattern (#4)

@amandarush https://github.com/amandarush No problem. I'm happy to create
the non-Genesis one from your Genesis code. Do you need help committing the
code for the Genesis one? I'm happy to help there as well. Just let me know!

**Comment by joedolson** [comment]
All patterns are in a single repo (a11ythemepatterns); you'd just need to pull down the repo and add a directory for your new pattern in an appropriate place.

**Comment by joedolson** [comment]
I went ahead and wrote and committed a pattern for this today; it was the only pattern we didn't have represented yet, so I felt it needed to happen. Anybody can feel free to add alternate patterns, but I'm closing this issue for now. Thanks!
