### ISSUE TITLE
New pattern suggestion: menu navigation with arrow keys

### ISSUE THREAD

**Issue by tellthemachines** [wpaccessibility/a11ythemepatterns#8]
I've got a bit of JS code for keyboard navigation of menus with arrow keys. Would love to contribute! Actually I have it in both vanilla JS and jQuery - which is best for the purposes of this repo?

**Comment by joedolson** [comment]
We actually like to have multiple copies of patterns, so having a pattern in vanilla JS and one in jQuery would be great. Thanks! Just make a pull request to incorporate the pattern.

**Comment by davidakennedy** [comment]
Closing this one out, since we have the code merged now. :smile:

**Comment by joedolson** [comment]
Works nicely, too. Added it to my own site.
